services:
  proxy:
    image: "traefik:2.11"
    ports:
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - "enchentes-app-br"
    command:
      - "--log.level=INFO"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=enchentes-app-br"

networks:
  enchentes-app-br:
    name: "enchentes-app-br"
