services:
  proxy:
    image: "traefik:2.11"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - "enchentes-app-br"
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--entrypoints.http.address=:80"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=enchentes-app-br"

networks:
  enchentes-app-br:
    name: "enchentes-app-br"
